[package]
name = "indy-vdr-proxy"
version = "0.1.1"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
description = "A basic proxy server exposing indy-vdr functionality over an HTTP interface"
edition = "2018"
license = "Apache-2.0"

[features]
fetch = ["hyper-tls"]
zmq_vendored = ["indy-vdr/zmq_vendored"]
default = ["fetch", "zmq_vendored"]

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
futures-util = "0.3.5"
hyper = "0.13.0"
hyper-tls = { version = "0.4.1", optional = true }
log = "0.4.8"
percent-encoding = "2.1.0"
serde_json = "1.0.40"
tokio = { version = "0.2.9", features = ["macros", "rt-util", "signal"] }
indy-vdr = { version = "0.3", path = "../libindy_vdr", default-features = false, features = ["log"] }

[target.'cfg(unix)'.dependencies]
hyper-unix-connector = "0.1.4"

[[bin]]
name = "indy-vdr-proxy"
path = "src/main.rs"
# NOTE suggest building release with feature "log/max_level_debug"
